# Generated by Django 5.1.2 on 2024-11-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_db',
            name='status_name',
            field=models.IntegerField(max_length=100),
        ),
    ]
