# Generated by Django 5.1.2 on 2024-11-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noiro', '0002_alter_status_db_status_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status_db',
            old_name='status_name',
            new_name='status',
        ),
    ]
