# Generated by Django 5.1.2 on 2024-11-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noiro', '0005_custom_user_project_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projest_role_db',
            new_name='Project_role_db',
        ),
    ]
