# Generated by Django 5.1.2 on 2024-11-27 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noiro', '0006_rename_projest_role_db_project_role_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_category_db',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noiro.project_db'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board_user_db',
            name='board_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Noiro.board_db'),
        ),
        migrations.AlterField(
            model_name='board_user_db',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
