# Generated by Django 5.1.2 on 2024-11-27 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noiro', '0007_work_category_db_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_work_category_db',
            name='board_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Noiro.board_db'),
        ),
        migrations.AddField(
            model_name='user_work_category_db',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Noiro.group_db'),
        ),
        migrations.AlterField(
            model_name='user_work_category_db',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
