# Generated by Django 5.1.2 on 2024-11-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noiro', '0009_remove_task_db_work_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_task_db',
            name='task_id',
        ),
    ]
