# Generated by Django 5.1.2 on 2024-12-19 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noiro', '0010_remove_user_task_db_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_category_db',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='task_db',
            name='user_task_id',
        ),
        migrations.AddField(
            model_name='user_task_db',
            name='user_task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Noiro.task_db'),
        ),
        migrations.DeleteModel(
            name='User_work_category_db',
        ),
        migrations.DeleteModel(
            name='Work_category_db',
        ),
    ]
