# Generated by Django 5.1.2 on 2024-12-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noiro', '0011_remove_work_category_db_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_task_db',
            name='user_task_id',
        ),
        migrations.AddField(
            model_name='user_task_db',
            name='task_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Noiro.task_db'),
            preserve_default=False,
        ),
    ]
