# Generated by Django 5.1.2 on 2024-12-19 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noiro', '0012_remove_user_task_db_user_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_db',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Noiro.project_db'),
            preserve_default=False,
        ),
    ]
