# Generated by Django 5.1.2 on 2024-12-24 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noiro', '0013_task_db_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task_db',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Noiro.project_db'),
            preserve_default=False,
        ),
    ]
